export default {
    AUTH_TOKEN: '',
    USER_ID:'',
    API_ENDPOINT: process.env.REACT_APP_API_ENDPOINT,
    DYNAMSOFT_PRODUCT_KEY: process.env.REACT_APP_DYNAMSOFT_PRODUCT_KEY,
    DYNAMSOFT_ORG_ID: process.env.REACT_APP_DYNAMSOFT_ORG_ID,
    GOOGLE_API_KEY: process.env.REACT_APP_GOOGLE_API_KEY,
    GOOGLE_BOOKS_API_ENDPOINT: ''
  };
  